repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        description: ''
        language: node
        entry: yarn eslint
        args:
          - --max-warnings=0
          - --no-warn-ignored
          - --pass-on-no-patterns
          - --report-unused-disable-directives
        types_or: [javascript, jsx, ts, tsx]
        minimum_pre_commit_version: '0'
        require_serial: false
        verbose: true

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    hooks:
      - id: clang-format
        name: clang-format
        description: ''
        # types_or: [java]
