enableGlobalCache: false

packageExtensions:
  '@aws-amplify/ui@*':
    dependencies:
      '@aws-amplify/core': '*'

  '@aws-amplify/ui-react-core@*':
    dependencies:
      'aws-amplify': '*'

yarnPath: .yarn/releases/yarn-4.6.0.cjs
