enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  '@angular/build@19':
    dependencies:
      '@angular/compiler': '^19.2.0'
      '@angular/core': '^19.2.0'
      'tslib': '^2.8.1'

  '@auth/drizzle-adapter@1.9':
    dependencies:
      'drizzle-orm': '^0.44.2'

  '@testing-library/jest-dom@6':
    dependencies:
      'vitest': '^3.2.3'

  'drizzle-kit@0.31':
    dependencies:
      '@libsql/client': '^0.15.9'
      'drizzle-orm': '^0.44.2'

yarnPath: ./.yarn/releases/yarn-4.9.1.js
