enableGlobalCache: false

packageExtensions:
  '@aws-amplify/storage@*':
    dependencies:
      '@aws-amplify/core': '*'

  '@aws-amplify/ui@*':
    dependencies:
      '@aws-amplify/core': '*'
      'xstate': '^4.33.6'

  '@aws-amplify/ui-react@*':
    dependencies:
      '@aws-amplify/core': '*'

  '@aws-amplify/ui-react-core@*':
    dependencies:
      'aws-amplify': '*'

  '@aws-amplify/ui-react-storage@*':
    dependencies:
      '@aws-amplify/storage': '6.7.8'

yarnPath: .yarn/releases/yarn-4.6.0.cjs
