name: Build and Deploy Boids Simulation

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Git LFS pull
        run: git lfs pull

      - name: Install dependencies
        run: yarn workspaces focus @turtleby/boids

      - name: Build project
        run: yarn workspaces foreach -Rpt --from @turtleby/boids run build --base /projects/boids-simulation/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          publish_dir: projects/boids/dist
          external_repository: laxsuryavanshi/laxsuryavanshi.github.io
          publish_branch: main
          destination_dir: projects/boids-simulation
          keep_files: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
